# Generated by Django 5.1.2 on 2024-12-17 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0002_alter_student_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance', models.CharField(blank=True, choices=[('Present', 'present'), ('Absent', 'absent')], default='Prsent', max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hod',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.faculty'),
        ),
    ]
