# Generated by Django 5.1.2 on 2024-12-31 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0009_course_created_at_course_updated_at_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
