# Generated by Django 5.1.2 on 2025-01-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0012_department_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
