# Generated by Django 5.1.2 on 2025-01-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0015_attendance_created_by_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
