# Generated by Django 5.1.2 on 2025-01-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0016_studentattendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CollegeApp.faculty'),
        ),
    ]
