# Generated by Django 5.1.2 on 2025-01-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0018_facultyattendancereport_studentattendancereport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyattendancereport',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentattendancereport',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10),
        ),
    ]
