# Generated by Django 5.1.2 on 2025-01-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0020_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hod',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.faculty'),
        ),
        migrations.AddField(
            model_name='hod',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
