# Generated by Django 5.1.2 on 2025-01-14 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0022_customuser_is_admin_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_hod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(related_name='faculties', to='CollegeApp.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_users', to='CollegeApp.department'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_department', to='CollegeApp.department'),
        ),
    ]
