# Generated by Django 5.1.2 on 2025-01-14 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0023_remove_subject_faculty_department_hod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_subjects', to='CollegeApp.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.faculty'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_subjects', to='CollegeApp.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
