# Generated by Django 5.1.2 on 2025-01-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0024_subject_course_id_subject_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='end_date',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='start_date',
            new_name='start_year',
        ),
    ]
