# Generated by Django 5.1.2 on 2025-01-15 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0025_rename_end_date_batch_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.batch'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.department'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='max_score',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.subject'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.faculty'),
        ),
    ]
